version: 1
formatters:
  basic:
    style: "{"
    format: "{asctime:s}:{levelname:s}:{name:s}:{message:s}"
handlers:
  console:
    class: logging.StreamHandler
    stream: ext://sys.stderr
    formatter: basic
  audit_file:
    class: logging.FileHandler
    filename: logs/audit.log
    formatter: basic
  connection_file:
    class: logging.FileHandler
    filename: logs/connections.log
    formatter: basic
  dev_file:
    class: logging.FileHandler
    filename: logs/dev.log
    formatter: basic
  web_file:
    class: logging.FileHandler
    filename: logs/web.log
    formatter: basic
  performance_file:
    class: logging.FileHandler
    filename: logs/performance.log
    formatter: basic
  db_file:
    class: logging.FileHandler
    filename: logs/db.log
    formatter: basic
loggers:
  verbose:
    handlers: [console]
    propagate: False
    level: INFO
  audit:
    handlers: [audit_file]
    level: INFO
    propagate: False
  connection:
    handlers: [connection_file]
    level: INFO
    propagate: False
  dev:
    handlers: [dev_file]
    level: INFO
    propagate: False
  web:
    handlers: [web_file]
    level: INFO
    propagate: False
  performance:
    handlers: [performance_file]
    level: INFO
    propagate: False
  db:
    handlers: [db_file]
    level: INFO
    propagate: False

root:
  handlers: [console]
  level: INFO


